# Generated by Django 5.0.6 on 2024-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('OTO', 'One-One'), ('GRP', 'Group')], default='OTO', max_length=3),
        ),
    ]
